[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.10.0"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
  # Or to fully disable (alternative):
  # SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "https://thesis-backend-wvmc.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200